mean_pkt_size = 1000# in bytes
qlimit_edgeports = 1 * (2 ** 20) # in bytes
qlimit_voq = 1 * (2 ** 20)  # in bytes
sdist = mean_pkt_size
sim_time = 2 #(1000 * (10 ** (-6)))
port_rate = 10 * 10 ** 9 # in bits per second
numOfInputPorts = 16
numOfOutputPorts = numOfInputPorts
numOfVOQsPerPort = numOfOutputPorts
num_gen = numOfInputPorts
gen_rate = 10**9
lk_delay = 6.5 *55* 10**-9